// Import Next.js Metadata type for SEO configuration
import type { Metadata } from "next";
// Import Google Fonts - Geist is a modern sans-serif font, Geist_Mono is for code/monospace text
import { Geist, Geist_Mono } from "next/font/google";
// Import global styles (Tailwind CSS + custom animations)
import "./globals.css";

// Configure the Geist Sans font
// - variable: Creates a CSS custom property --font-geist-sans that can be used throughout the app
// - subsets: Only loads the Latin character set to reduce font file size
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configure the Geist Mono font (monospace font for code or technical text)
// - variable: Creates a CSS custom property --font-geist-mono
// - subsets: Only loads the Latin character set
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata configuration for SEO and browser tab display
// This object is exported and used by Next.js for page metadata
export const metadata: Metadata = {
  title: "Create Next App", // Browser tab title
  description: "Generated by create next app", // Meta description for search engines
};

// Root Layout Component
// This is the top-level layout that wraps the entire application
// All pages will be rendered inside the {children} placeholder
export default function RootLayout({
  children, // The page content that will be rendered (page.tsx)
}: Readonly<{
  children: React.ReactNode; // Type: any valid React component or element
}>) {
  return (
    // HTML root element - lang="en" for accessibility and SEO
    <html lang="en">
      {/* Body element with font variables applied via CSS classes */}
      <body
        // Apply both font variables and antialiased class for smoother text rendering
        // ${geistSans.variable} adds --font-geist-sans CSS variable
        // ${geistMono.variable} adds --font-geist-mono CSS variable
        // antialiased is a Tailwind class for font smoothing
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* This is where page.tsx content gets injected */}
        {children}
      </body>
    </html>
  );
}
